/**
 * NOVA cloud inference.
 *
 * Cloud answers are generated by the platform's managed AI runtime. The
 * gateway key is server-only. Local inference never reaches this module.
 */
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { getPlanLimits } from "@/lib/plans";

const GATEWAY_URL = "https://ai.gateway.lovable.dev/v1/chat/completions";
const RUNTIME_MODEL = "openai/gpt-6-astra";

const MODE_EFFORT: Record<string, "low" | "medium" | "high"> = {
  "nova-auto": "medium",
  "nova-fast": "low",
  "nova-reasoning": "high",
  "nova-coding": "medium",
  "nova-research": "high",
};

const CLOUD_MODES = Object.keys(MODE_EFFORT) as [string, ...string[]];

const ChatInput = z.object({
  messages: z.array(
    z.object({
      role: z.enum(["system", "user", "assistant"]),
      content: z.string().min(1).max(100_000),
    }),
  ).min(1).max(100),
  model: z.enum(CLOUD_MODES),
  temperature: z.number().min(0).max(2).optional(),
  maxTokens: z.number().int().min(1).max(32_000).optional(),
});

function friendlyError(status: number, message: string): string {
  if (status === 402) return message || "NOVA's AI allowance is used up. Add credits to keep generating answers.";
  if (status === 403) return message || "AI access is blocked for this workspace.";
  if (status === 429) return "NOVA is being rate limited right now. Please try again in a few seconds.";
  return message || "AI request failed (" + status + ").";
}

function startOfUtcDay(): string {
  const now = new Date();
  now.setUTCHours(0, 0, 0, 0);
  return now.toISOString();
}

/** Cloud chat completion through the managed runtime. Signed-in users only. */
export const novaCloudChat = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((input: unknown) => ChatInput.parse(input))
  .handler(async ({ data, context }) => {
    const apiKey = process.env["LOVABLE_API_KEY"];
    const empty = {
      content: "",
      tokensInput: 0,
      tokensOutput: 0,
      upstreamModel: "",
      provider: "nova_cloud" as const,
    };

    if (!apiKey) return { ...empty, error: "NOVA's AI runtime is not available in this environment." };

    const { userId, supabase } = context;
    const { data: profile, error: profileError } = await supabase
      .from("profiles")
      .select("plan")
      .eq("id", userId)
      .maybeSingle();

    if (profileError || !profile) {
      return { ...empty, error: "Your NOVA profile could not be verified. Please sign in again." };
    }

    const plan = profile.plan;
    const limits = getPlanLimits(plan);
    if (!limits.allowed_models.includes(data.model)) {
      return { ...empty, error: "The " + data.model + " mode is not available on your current plan." };
    }

    const { count, error: usageError } = await supabase
      .from("usage_records")
      .select("id", { count: "exact", head: true })
      .eq("user_id", userId)
      .eq("resource_type", "chat_message")
      .gte("created_at", startOfUtcDay());

    if (usageError) {
      return { ...empty, error: "NOVA could not verify today's usage. Please try again." };
    }
    if ((count ?? 0) >= limits.max_messages_per_day) {
      return { ...empty, error: "You've reached your " + plan + " plan's daily message limit. Try again tomorrow." };
    }

    const upstreamModel = RUNTIME_MODEL;
    const effort = MODE_EFFORT[data.model] ?? MODE_EFFORT["nova-auto"];

    try {
      const response = await fetch(GATEWAY_URL, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Lovable-API-Key": apiKey,
          "X-Lovable-AIG-SDK": "fetch",
        },
        body: JSON.stringify({
          model: upstreamModel,
          messages: data.messages,
          reasoning_effort: effort,
          max_completion_tokens: data.maxTokens ?? 4000,
        }),
      });

      if (!response.ok) {
        const detail = await response.text();
        let message = detail.slice(0, 400);
        try {
          const parsed = JSON.parse(detail) as { error?: { message?: string }; message?: string };
          message = parsed.error?.message ?? parsed.message ?? message;
        } catch {
          // Keep the upstream text.
        }
        return { ...empty, error: friendlyError(response.status, message) };
      }

      const body = (await response.json()) as {
        choices?: Array<{ message?: { content?: string } }>;
        usage?: { prompt_tokens?: number; completion_tokens?: number };
      };
      const content = body.choices?.[0]?.message?.content ?? "";
      const tokensInput = body.usage?.prompt_tokens ?? 0;
      const tokensOutput = body.usage?.completion_tokens ?? 0;

      if (!content.trim()) return { ...empty, error: "The AI runtime returned an empty response." };

      const { error: insertUsageError } = await supabase.from("usage_records").insert({
        user_id: userId,
        resource_type: "chat_message",
        model: data.model,
        provider: "nova_cloud",
        tokens_input: tokensInput,
        tokens_output: tokensOutput,
      });

      if (insertUsageError) console.error("Failed to record cloud usage:", insertUsageError.message);

      return {
        content,
        tokensInput,
        tokensOutput,
        upstreamModel,
        provider: "nova_cloud" as const,
        error: null as string | null,
      };
    } catch (err) {
      return {
        ...empty,
        error: err instanceof Error ? err.message : "Cloud AI request failed",
      };
    }
  });

export const novaCloudStatus = createServerFn({ method: "GET" })
  .middleware([requireSupabaseAuth])
  .handler(async () => ({ available: Boolean(process.env["LOVABLE_API_KEY"]) }));
