/**
 * NOVA cloud inference.
 *
 * Cloud answers are generated by the platform's built-in, managed AI runtime.
 * The key is read on the server only and never reaches the browser. There is
 * no user-facing provider or API-key configuration anywhere in NOVA.
 *
 * Local inference (Ollama) never reaches this file — it runs on the user's own
 * machine and is called directly from the browser.
 */
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";

const GATEWAY_URL = "https://ai.gateway.lovable.dev/v1/chat/completions";

/** The managed runtime model NOVA's cloud modes are answered by. */
const RUNTIME_MODEL = "openai/gpt-6-astra";

/** How much thinking each NOVA mode gets. */
const MODE_EFFORT: Record<string, "low" | "medium" | "high"> = {
  "nova-auto": "medium",
  "nova-fast": "low",
  "nova-reasoning": "high",
  "nova-coding": "medium",
  "nova-research": "high",
};

const DEFAULT_MODE = "nova-auto";

const ChatInput = z.object({
  messages: z
    .array(
      z.object({
        role: z.enum(["system", "user", "assistant"]),
        content: z.string(),
      }),
    )
    .min(1),
  model: z.string().min(1),
  temperature: z.number().min(0).max(2).optional(),
  maxTokens: z.number().int().min(1).max(32000).optional(),
});

function friendlyError(status: number, message: string): string {
  if (status === 402) {
    return message || "NOVA's AI allowance is used up. Add credits to keep generating answers.";
  }
  if (status === 403) {
    return message || "AI access is blocked for this workspace.";
  }
  if (status === 429) {
    return "NOVA is being rate limited right now. Please try again in a few seconds.";
  }
  return message || `AI request failed (${status}).`;
}

/** Cloud chat completion through the managed runtime. Signed-in users only. */
export const novaCloudChat = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((input: unknown) => ChatInput.parse(input))
  .handler(async ({ data }) => {
    const apiKey = process.env["LOVABLE_API_KEY"];
    const empty = {
      content: "",
      tokensInput: 0,
      tokensOutput: 0,
      upstreamModel: "",
      provider: "nova_cloud" as const,
    };

    if (!apiKey) {
      return { ...empty, error: "NOVA's AI runtime is not available in this environment." };
    }

    const upstreamModel = RUNTIME_MODEL;
    const effort = MODE_EFFORT[data.model] ?? MODE_EFFORT[DEFAULT_MODE]!;

    try {
      const response = await fetch(GATEWAY_URL, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Lovable-API-Key": apiKey,
          "X-Lovable-AIG-SDK": "fetch",
        },
        body: JSON.stringify({
          model: upstreamModel,
          messages: data.messages,
          reasoning_effort: effort,
          max_completion_tokens: data.maxTokens ?? 4000,
        }),
      });

      if (!response.ok) {
        const detail = await response.text();
        let message = detail.slice(0, 400);
        try {
          const parsed = JSON.parse(detail) as { error?: { message?: string }; message?: string };
          message = parsed.error?.message ?? parsed.message ?? message;
        } catch {
          /* keep raw text */
        }
        return { ...empty, error: friendlyError(response.status, message) };
      }

      const body = (await response.json()) as {
        choices?: Array<{ message?: { content?: string } }>;
        usage?: { prompt_tokens?: number; completion_tokens?: number };
      };

      return {
        content: body.choices?.[0]?.message?.content ?? "",
        tokensInput: body.usage?.prompt_tokens ?? 0,
        tokensOutput: body.usage?.completion_tokens ?? 0,
        upstreamModel,
        provider: "nova_cloud" as const,
        error: null as string | null,
      };
    } catch (err) {
      return {
        ...empty,
        error: err instanceof Error ? err.message : "Cloud AI request failed",
      };
    }
  });

/** Confirms the managed runtime is available. No keys, no providers exposed. */
export const novaCloudStatus = createServerFn({ method: "GET" })
  .middleware([requireSupabaseAuth])
  .handler(async () => ({ available: Boolean(process.env["LOVABLE_API_KEY"]) }));
