/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AutomationsRouteImport } from './routes/automations'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as FilesRouteImport } from './routes/files'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as ChatConversationIdRouteImport } from './routes/chat.$conversationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsRoute = AutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatConversationIdRoute = ChatConversationIdRouteImport.update({
  id: '/$conversationId',
  path: '/$conversationId',
  getParentRoute: () => ChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/automations': typeof AutomationsRoute
  '/chat': typeof ChatRouteWithChildren
  '/files': typeof FilesRoute
  '/knowledge': typeof KnowledgeRoute
  '/memory': typeof MemoryRoute
  '/projects': typeof ProjectsRoute
  '/research': typeof ResearchRoute
  '/search': typeof SearchRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/timeline': typeof TimelineRoute
  '/usage': typeof UsageRoute
  '/chat/$conversationId': typeof ChatConversationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/automations': typeof AutomationsRoute
  '/chat': typeof ChatRouteWithChildren
  '/files': typeof FilesRoute
  '/knowledge': typeof KnowledgeRoute
  '/memory': typeof MemoryRoute
  '/projects': typeof ProjectsRoute
  '/research': typeof ResearchRoute
  '/search': typeof SearchRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/timeline': typeof TimelineRoute
  '/usage': typeof UsageRoute
  '/chat/$conversationId': typeof ChatConversationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/automations': typeof AutomationsRoute
  '/chat': typeof ChatRouteWithChildren
  '/files': typeof FilesRoute
  '/knowledge': typeof KnowledgeRoute
  '/memory': typeof MemoryRoute
  '/projects': typeof ProjectsRoute
  '/research': typeof ResearchRoute
  '/search': typeof SearchRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/timeline': typeof TimelineRoute
  '/usage': typeof UsageRoute
  '/chat/$conversationId': typeof ChatConversationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/automations'
    | '/chat'
    | '/files'
    | '/knowledge'
    | '/memory'
    | '/projects'
    | '/research'
    | '/search'
    | '/security'
    | '/settings'
    | '/tasks'
    | '/timeline'
    | '/usage'
    | '/chat/$conversationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/automations'
    | '/chat'
    | '/files'
    | '/knowledge'
    | '/memory'
    | '/projects'
    | '/research'
    | '/search'
    | '/security'
    | '/settings'
    | '/tasks'
    | '/timeline'
    | '/usage'
    | '/chat/$conversationId'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/automations'
    | '/chat'
    | '/files'
    | '/knowledge'
    | '/memory'
    | '/projects'
    | '/research'
    | '/search'
    | '/security'
    | '/settings'
    | '/tasks'
    | '/timeline'
    | '/usage'
    | '/chat/$conversationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  AutomationsRoute: typeof AutomationsRoute
  ChatRoute: typeof ChatRouteWithChildren
  FilesRoute: typeof FilesRoute
  KnowledgeRoute: typeof KnowledgeRoute
  MemoryRoute: typeof MemoryRoute
  ProjectsRoute: typeof ProjectsRoute
  ResearchRoute: typeof ResearchRoute
  SearchRoute: typeof SearchRoute
  SecurityRoute: typeof SecurityRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
  TimelineRoute: typeof TimelineRoute
  UsageRoute: typeof UsageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations': {
      id: '/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$conversationId': {
      id: '/chat/$conversationId'
      path: '/$conversationId'
      fullPath: '/chat/$conversationId'
      preLoaderRoute: typeof ChatConversationIdRouteImport
      parentRoute: typeof ChatRoute
    }
  }
}

interface ChatRouteChildren {
  ChatConversationIdRoute: typeof ChatConversationIdRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatConversationIdRoute: ChatConversationIdRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  AutomationsRoute: AutomationsRoute,
  ChatRoute: ChatRouteWithChildren,
  FilesRoute: FilesRoute,
  KnowledgeRoute: KnowledgeRoute,
  MemoryRoute: MemoryRoute,
  ProjectsRoute: ProjectsRoute,
  ResearchRoute: ResearchRoute,
  SearchRoute: SearchRoute,
  SecurityRoute: SecurityRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
  TimelineRoute: TimelineRoute,
  UsageRoute: UsageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
